#!/bin/sh

# Use neovim for vim when possible.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# adds verbosity where we like it and shortens common commands.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
    sudo="doas" \
  	ka="killall" \
	g="git" \
    sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="doas apt " \
    l="ls -lia" \
    la="ls -a"

# adds color to commands.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
    xterm="urxvt" \
    btop="btop -t -lc" \
    bpytop="bpytop -lc" \
    neofetch="neofetch --ascii_distro freebsd"


